### ISSUE TITLE
Project configuration file

### ISSUE THREAD

**Issue by iacopy** [iacopy/RCSB-Sync#53]
E.g. in YAML:

```yaml
---
taxa:
  - Homo sapiens
  - Mus musculus
  - Rattus norvegicus
methods:
  - X-RAY DIFFRACTION
  - SOLUTION NMR
  - ELECTRON MICROSCOPY
polymer_type:
  - Protein
results_content_type:
  - computational
  - experimental
...
```

* https://hackersandslackers.com/simplify-your-python-projects-configuration/
* https://towardsdatascience.com/from-novice-to-expert-how-to-write-a-configuration-file-in-python-273e171a8eb3
